name: fabspinrider
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.3+5

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  get:
  google_maps_flutter: ^2.3.0
  geolocator: ^13.0.1
  geocoding: ^2.1.0
  http: ^0.13.6
  flutter_polyline_points: ^1.0.0
  image_picker: ^1.1.2
  ionicons:
  permission_handler: ^11.3.1
  shared_preferences:
  url_launcher: ^6.3.0
  flutter_local_notifications:
  firebase_messaging:
  php_serializer:

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  firebase_core: ^3.12.0
  path_provider: ^2.1.5
  image_cropper: ^4.0.1
  camera: ^0.11.0+2
  video_player: ^2.9.2
  http_parser: ^4.0.2
  mime: ^2.0.0
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app-icon.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/otp.png
    - assets/images/otp1.png
    - assets/images/garment-cleaning.jpg
    - assets/images/shoe-cleaning.jpg
    - assets/images/carpet-cleaning.jpg
    - assets/images/sofa-cleaning.jpg
    - assets/icon/confirmOrder.gif
    - assets/images/bg.jpg
    - assets/icon/splash.png
    - assets/images/Fabspin.png
    - assets/images/Fabspin.jpeg
    - assets/images/banner2.gif
    - assets/images/banner1.gif
    - assets/images/banner3.jpeg
    - assets/images/bannersmall.gif
    - assets/images/promotion1.jpeg
    - assets/images/promotion2.jpeg
    - assets/images/rider.webp
    - assets/icon/app-icon.jpg

